### ISSUE TITLE
Add satysfi-lib

### ISSUE THREAD

**Issue by na4zagin3** [na4zagin3/satyrographos-repo#15]
Repository: https://github.com/nyuichi/satysfi-lib

Questions/Issues
- Is the package name `satysfi-lib` or simply `lib`?
- Need to send a MR to structure tests and dependent libraries (i.e., zrbase)

**Comment by nyuichi** [comment]
Closing this?

**Comment by na4zagin3** [comment]
Good catch! It should have been closed with #33. Closing.
