### ISSUE TITLE
Apply CC0-1.0+ license

### ISSUE THREAD

**Issue by na4zagin3** [na4zagin3/satyrographos-repo#334]
In order to increase ~~contributors~~ maintainers, this repository need to have a license.  I believe CC0 is the best, considering that there are jurisdictions (e.g., Japan) where an author cannot declare their works public domain.  Also we can be align with the [official OPAM Repository](https://github.com/ocaml/opam-repository#license), whose contents are currently licensed under `CC0-1.0`.

**For the contributors and the authors, can you please leave a comment below if you agree or disagree applying `CC0-1.0+` (CC0 1.0 Universal or _later version_) to the entire repository?**

Here is the list of the contributors.

- [x] @abenori
- [x] @amutake
- [x] @monaqa
- [x] @na4zagin3
- [x] @namachan10777
- [x] @nyuichi
- [x] @puripuri2100
- [x] @uemurax
- [x] @yuhr
- [x] @zeptometer

Here is the list of the authors whose OPAM files that are submitted by other contributors.

- [x] @gfngfn
- [x] @nekketsuuu

Both lists are in alphabetical order.

Although I think agreement is not strictly required in this case, I'd like to make it completely legal.

**Comment by amutake** [comment]
agree 🙆‍♂️

**Comment by puripuri2100** [comment]
agree

**Comment by na4zagin3** [comment]
I, of course, agree to apply the `CC0-1.0+` license to my contributions.

**Comment by nekketsuuu** [comment]
agree 🙆‍♂️

**Comment by yuhr** [comment]
Definitely agree!

**Comment by monaqa** [comment]
Agreed!

**Comment by zeptometer** [comment]
sounds good!

**Comment by nyuichi** [comment]
Agreed <3

**Comment by gfngfn** [comment]
I would also like to agree🙆‍♂️

**Comment by uemurax** [comment]
I agree.

**Comment by abenori** [comment]
I agree.

**Comment by namachan10777** [comment]
Agree. :ok_man:

**Comment by na4zagin3** [comment]
Everyone agreed.  I'm closing the vote and applying the change.  Thank you everyone!
