### ISSUE TITLE
satysfi-dist: Fix URLs of fonts from GUST

### ISSUE THREAD

**Issue by na4zagin3** [na4zagin3/satyrographos-repo#575]
https://github.com/gfngfn/SATySFi/issues/411

**Comment by kyori19** [comment]
I want to fix this problem, and tried changing archive URL to https in my fork. (ref: https://github.com/kyori19/satyrographos-repo/commit/b2ff068ddd64999d26c2db78b9b4a1961c4aecfe)

Is it correct to edit `satysfi-dist/satysfi-dist.x.x.x/opam` manually? If so, I will create PR for you.

**Comment by na4zagin3** [comment]
Hi @kyori19,

> Is it correct to edit satysfi-dist/satysfi-dist.x.x.x/opam manually? If so, I will create PR for you.

Yes, exactly!

Thank you so much for your help m(_ _)m

**Comment by kyori19** [comment]
@na4zagin3 thanks, I have just created PR #582.
